sudo: false
dist: xenial

language: php

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 8.1.0
      env: WP_VERSION=latest
    - php: 8.0.0
      env: WP_VERSION=latest
    - php: 7.4.0
      env: WP_VERSION=latest
    - php: 7.3.27
      env: WP_VERSION=latest

before_script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
      composer update
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      ./vendor/bin/phpunit --configuration ./phpunit.xml.dist
      WP_MULTISITE=1 ./vendor/bin/phpunit --configuration ./phpunit.xml.dist
    fi
